### ISSUE TITLE
应用会通过notificationToken来分析是否为风险用户,这个该如何解决?

### ISSUE THREAD

**Issue by a978069486** [dandar3/android-google-firebase-installations#1]

**Comment by dandar3** [comment]
Please state your issue or this will be closed at the end of the day, thank you.

**Comment by a978069486** [comment]
我使用您这个SDK去获取token,然后提交到应用上(该应用注册的时候需要带上token),注册不通过是怎么回事

**Comment by dandar3** [comment]
> (Google Translate) I use your SDK to obtain the token, and then submit it to the application (the application needs to bring the token when registering), what is the matter if the registration fails?

How do you use the library (some code snippet?) and what is the failure exactly?

**Comment by dandar3** [comment]
Hi @a978069486 

I suggest reading the README.md below, pick a top level project you need and import that as a project set (see the video at the end on how to do that) and then try again. You also have there some reference blog posts that might help.

https://github.com/dandar3/android-google-firebase-README
